language: go

go:
  - 1.8.x

branches:
  only:
    - master

script:
  - go get github.com/Masterminds/glide
  - glide i
  - go test -v $(go list ./... | grep -v /vendor/)
  - go build -v .

after_success:
  - test $TRAVIS_PULL_REQUEST = false && if [ "$TRAVIS_BRANCH" == "master" ];then curl -i -H "$AUTH" "$DEPLOY_URL"; fi; exit 0

