language: go

go:
  - 1.7.x

branches:
  only:
    - master

script:
  - go test -v .
  - go build -v .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      curl -i -H "$AUTH" "$DEPLOY_URL"
    fi

