language: go

go:
  - 1.7.x

branches:
  only:
    - master

script:
  - go test -v .
  - go build -v .

after_success:
  - test $TRAVIS_PULL_REQUEST = false && if [ "$TRAVIS_BRANCH" == "master" ];then curl -i -H "$AUTH" "$DEPLOY_URL"; fi
  - exit 0

